### ISSUE TITLE
No es posible hacer uso de la visualización completa de datos de una persona.

### ISSUE THREAD

**Issue by Marcelo2m97** [DJNGOSolutions/DUI-OCR-Panel#1]
He intentado hacer uso del botón para poder visualizar todos los datos de una sola persona, pero aparentemente no funciona, ya que le he dado clic y no obtengo ningún tipo de respuesta.

![Issue1](https://user-images.githubusercontent.com/32823109/87498914-38a2e080-c616-11ea-84f8-0ca52b0e9818.png)

**Comment by tupic98** [comment]
Ya se solucionó el bug. No se estaba mandando el id correcto.
