### ISSUE TITLE
Ya existe una conexion entre la base de datos y la API?

### ISSUE THREAD

**Issue by RonaldVega14** [DJNGOSolutions/DUI-OCR-Panel#3]
Ya tiene conexiones con API y base de datos para mantener la persistencia o sigue ocupando datos estaticos?

**Comment by Marcelo2m97** [comment]
Por el momento, aún se tienen datos estáticos en la aplicación, todavía se está desarrollando la conexión con una API. Te informaremos cuando hagamos el primer realese la aplicación.

**Comment by tupic98** [comment]
Solucionado
